@startuml uc_paciente
skinparam shadowing false
skinparam packageStyle rectangle
skinparam defaultFontName Arial

left to right direction
skinparam actorStyle awesome

rectangle "MiDentista" {
  usecase "Registrarse con su correo" as D1
  usecase "Buscar y afiliarse a su clinica" as D2
  usecase "Consultar sus citas" as D3
  usecase "Consultar sus presupuestos y estado de cuenta" as D4
  usecase "Ver sus datos clinicos (historia y odontograma)" as D5
}

actor "Paciente" as PAC
PAC --> D1
PAC --> D2
PAC --> D3
PAC --> D4
PAC --> D5
@enduml